#Delivery Pipeline for our clusters

apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: gitops
description: main application pipeline
serialPipeline:
  stages:
  - targetId: qsdev
  - targetId: qsprod
---

#Our 1st Cluster TARGET
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: qsdev
description: development cluster
gke:
 cluster:  projects/prefab-faculty-438111-k7/locations/us-central1-a/clusters/dev-cluster
executionConfigs:
- defaultPool:
    serviceAccount: gke-cicd-hackathon-project@prefab-faculty-438111-k7.iam.gserviceaccount.com
  usages:
  - RENDER 
  - DEPLOY   
---
#Our 2st Cluster TARGET

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: qsprod
description: production cluster
requireApproval: true
gke:
 cluster:  projects/prefab-faculty-438111-k7/locations/us-central1-a/clusters/stage-cluster
executionConfigs:
- defaultPool:
    serviceAccount: gke-cicd-hackathon-project@prefab-faculty-438111-k7.iam.gserviceaccount.com
  usages:
  - RENDER 
  - DEPLOY
