apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: git-ops
build:
  artifacts:
  - image: html-img=us-central1-docker.pkg.dev/prefab-faculty-438111-k7/gke-repo/html-img:latest
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - deployment.yaml
  
